### ISSUE TITLE
Blurry images

### ISSUE THREAD

**Issue by Fhealz** [aneaville/MMM-GooglePhotos#123]
Hi All
I've installed MM and everything is running well. Config setting of showWidth 1920, and showHeight 1080 with fullscreen-below.
The image are very blurry, maybelow resolution. Anyone else with this situation. I must be missing something. I have tried adjusting the custom.css to no avail. 
Still a noob, thanks.

**Comment by tddrane** [comment]
Perhaps you could post one sample photo here (in its original resolution.) 
If you look at the same photos in Google Photos on a similar monitor, are they blurry there as well?

**Comment by Fhealz** [comment]
Here are the 2 images, as you can see it is large on MM display. I have played with the config.js and set fall setting to 800X600.
I went to the custom.css and tried setting to "contain" from "cover" it changed nothing. Sent copy of latest Config.js.
Thanks in advance for any help.

[image](https://user-images.githubusercontent.com/94768334/142907470-e0e83364-e51d-4632-8f7f-873ae4d344f1.png)
[image](https://user-images.githubusercontent.com/94768334/142907773-8606923c-3c77-49d7-a04c-99f506c5a380.png)
[GPconfig.txt](https://github.com/aneaville/MMM-GooglePhotos/files/7583376/GPconfig.txt)

**Comment by tddrane** [comment]
Was the image less blurry when you set the width and height to 1920X1080?
Have you tried using larger numbers. Can't tell what size your Toshiba monitor is from the photo.
What happens when you set the position to fullscreen_above ?

And a shot in the dark, have you tried:

Not to show blurred Background : Add this into your css/custom.css.

#GPHOTO_BACK {
	display:none;
}

**Comment by Fhealz** [comment]
The Toshiba is a TV. But it is the same on a 1920x 1080 monitor. Have not tried fullscreen_above, will tonight. I will add to css tonight. It looks as if it is blown up to much and low resolution. I placed an image that was 3728 x 2536 and still the same results. Its been driving me crazy for 4 days now.
Thank you I will try these and get back tonight.

**Comment by tddrane** [comment]
I re-enabled the background on my MM and found that it had muted colors. I though originally that it was black and white.  Your image has muted colors as well as low resolution so I think you will see a difference if you do add the suggestion to custom.css. 
I only run the clock on my MM and only because it enables the GPHOTO_INFO as noted in my yet unanswered post. 
You may want to comment out some of the other modules in the config.js file to see if any of them are affecting the MMM-GooglePhotos module.
    On Monday, November 22, 2021, 05:37:30 PM EST, Fhealz ***@***.***> wrote:  
 
 


The Toshiba is a TV. But it is the same on a 1920x 1080 monitor. Have not tried fullscreen_above, will tonight. I will add to css tonight. It looks as if it is blown up to much and low resolution. I placed an image that was 3728 x 2536 and still the same results. Its been driving me crazy for 4 days now.
Thank you I will try these and get back tonight.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Fhealz** [comment]
I just tried the recommended Config.js and custom.css settings to no avail. No image at all. Yes you are correct its like the blurred on the sides, without the image. I'll try comenting out some of the Modules. If not I'll try a new install. I'll let you know.

**Comment by aneaville** [comment]
In your config, can you try increasing the resolution here to match your screen:

showWidth: 1920, // These values will be used for quality of downloaded photos to show. real size to show in your MagicMirror region is recommended.
showHeight: 1080,

**Comment by tddrane** [comment]
If, with the custom.css option, you are getting no image at all then what you were getting was the background.
Here is my config.js content you can try You will need to change the albums: and the resolution : All modules but Clock are commented out.

Edited to add file as attachment to preserve formatting.





    On Monday, November 22, 2021, 06:17:24 PM EST, Fhealz ***@***.***> wrote:  
 
 


[td-config.js.txt](https://github.com/aneaville/MMM-GooglePhotos/files/7585197/td-config.js.txt)




I just tried the recommended Config.js and custom.css settings to no avail. No image at all. Yes you are correct its like the blurred on the sides, without the image. I'll try comenting out some of the Modules. If not I'll try a new install. I'll let you know.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Fhealz** [comment]
So I commented everything out and still same results. Probably a line or comma didn't install correctly. I don'T know how that could happen, but I've done everything else.I'm going to reinstall in a couple of minutes. If that does not work I'll have to use a differant Mod for images. I'll let you know

**Comment by Fhealz** [comment]
So when I hit npm install I got this
pi@raspberrypi:~/MMM-GooglePhotos $ npm install
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated axios@0.18.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm notice created a lockfile as package-lock.json. You should commit this file.
added 203 packages from 140 contributors and audited 203 packages in 23.009s

6 packages are looking for funding
  run `npm fund` for details

found 13 vulnerabilities (7 moderate, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by Fhealz** [comment]
I cannot get it to install. I think I'll move on till it get straightened out. Cannot rebuild Electron.
This is a little beyond me.

**Comment by Fhealz** [comment]
pi@raspberrypi:~/MMM-GooglePhotos $ ./node_modules/.bin/electron-rebuild   # It could takes dozens sec.

An unhandled error occurred inside electron-rebuild
Unable to find electron's version number, either install it or specify an explicit version

Error: Unable to find electron's version number, either install it or specify an explicit version
    at /home/pi/MMM-GooglePhotos/node_modules/electron-rebuild/lib/src/cli.js:87:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/pi/MMM-GooglePhotos/node_modules/electron-rebuild/lib/src/cli.js:6:58)
pi@raspberrypi:~/MMM-GooglePhotos $ cd ~/MagicMirror/modules/MMM-GooglePhotos
bash: cd: /home/pi/MagicMirror/modules/MMM-GooglePhotos: No such file or directory
pi@raspberrypi:~/MMM-GooglePhotos $ npm install --save-dev electron-rebuild
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
+ electron-rebuild@1.11.0
updated 1 package and audited 204 packages in 8.792s

3 packages are looking for funding
  run `npm fund` for details

found 11 vulnerabilities (7 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
pi@raspberrypi:~/MMM-GooglePhotos $ ./node_modules/.bin/electron-rebuild   # It could takes dozens sec.

An unhandled error occurred inside electron-rebuild
Unable to find electron's version number, either install it or specify an explicit version

Error: Unable to find electron's version number, either install it or specify an explicit version
    at /home/pi/MMM-GooglePhotos/node_modules/electron-rebuild/lib/src/cli.js:87:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/pi/MMM-GooglePhotos/node_modules/electron-rebuild/lib/src/cli.js:6:58)
pi@raspberrypi:~/MMM-GooglePhotos $

**Comment by tddrane** [comment]
This looks a lot like my first attempt to get the module working on an ARM6 pi. I could get MM to run but not GooglePhotos. I was able to run it successfully on an ARM7 pi.

**Comment by Fhealz** [comment]
I'm running a RPI4. This shouldn't be a problem.


processor	: 0
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 270.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 270.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 270.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
model name	: ARMv7 Processor rev 3 (v7l)

**Comment by Fhealz** [comment]
So today I formatted a new card and loaded the RPI OS and installed MM2. It still comes back with 11 vulnerabilities 4 being high. I cannot install GooglePhotos. There has to be an answer for this, its crazy.

**Comment by tddrane** [comment]
Did you do this:?:
run npm audit fix to fix them, or npm audit for details

My installation went better once I performed the npm fix.

**Comment by Fhealz** [comment]
Yes it only fixed 2 issues. I'm trying a couple of things today and tomorrow that are a little out there. I'll let you know

**Comment by Fhealz** [comment]
Well I finally found out what it was. Turns out the 0auth was off by one number. It was not being carried over properly.
Thank you for taking the time to help me. The way I figured it out is, was pasting all the codes I was dealing with into a text file and noticed the differance. I usually figure this stuff out faster then this. LOL
Thank you again.

**Comment by tddrane** [comment]
Glad it is working for you now. How odd that it would retrieve any photo at all, albeit low resolution if the authorization wasn't valid. 
    On Wednesday, November 24, 2021, 06:09:11 PM EST, Fhealz ***@***.***> wrote:  
 
 


Well I finally found out what it was. Turns out the 0auth was off by one number. It was not being carried over properly.
Thank you for taking the time to help me. The way I figured it out is, was pasting all the codes I was dealing with into a text file and noticed the differance. I usually figure this stuff out faster then this. LOL
Thank you again.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Fhealz** [comment]
I have not been able to reproduce any of the errors or vulnerabilities that I recieved during install. I wonder if there was just something wrong with the install from the get go. 
Good question: Why did it get any even Low Res. pics, when it should not have recieved anything?
