### ISSUE TITLE
"missing Credentials"  error

### ISSUE THREAD

**Issue by piegolf** [aneaville/MMM-GooglePhotos#124]
wouldn't load in magicmirror, checked logs and found this error
[05.12.2021 14:14.29.725] [ERROR] (node:13260) UnhandledPromiseRejectionWarning: Error: Missing Credentials.
    at new Auth (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:31:11)
    at GPhotos.onAuthReady (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:130:14)
    at /home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:205:12
    at new Promise (<anonymous>)
    at GPhotos.getAlbumType (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:204:12)
    at step (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:183:35)
    at /home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:197:7
    at new Promise (<anonymous>)
    at GPhotos.getAlbums (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:180:12)
    at step (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_helper.js:192:33)

**Comment by piegolf** [comment]
i forgot to enable the GooglePhotos API, once i enabled the API it loaded and there were no errors in logs
