### ISSUE TITLE
Photos Not Displaying

### ISSUE THREAD

**Issue by wroantree** [aneaville/MMM-GooglePhotos#128]
I installed the module yesterday but it's not displaying any photos. The photoListCache.json file is populated with all of the pictures in the shared album. I looked through issues 116 and 125 which seemed similar but I didn't find any resolution there. I have both Google Photos Library and Google+ enabled. This is a portion of the error log:

/home/pi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT
/home/pi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT
/home/pi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT
/home/pi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT
/home/pi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT
/home/pi/MagicMirror/node_modules/electron/dist/electron exited with signal SIGINT
[28.12.2021 20:26.11.083] [ERROR] (node:5486) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/adapters/http.js:293:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `electron --trace-warnings ...` to show where the warning was created)
[28.12.2021 20:26.11.092] [ERROR] (node:5486) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[28.12.2021 20:26.11.096] [ERROR] (node:5486) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[28.12.2021 20:26.14.231] [ERROR] (node:5486) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/adapters/http.js:293:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[28.12.2021 20:26.14.233] [ERROR] (node:5486) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[28.12.2021 20:27.08.417] [ERROR] (node:5486) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/adapters/http.js:293:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

Can you please help me to get this working? Thanks!

**Comment by aneaville** [comment]
There are several status code 400 responses which means 'bad request'. 

You can search the previous issues for the 400 response code, or post your config and I'll see if anything stands out.
