### ISSUE TITLE
Photos don't show up 25% of the time

### ISSUE THREAD

**Issue by rmcelwee** [aneaville/MMM-GooglePhotos#132]
I have my MM set to reboot every 6 hours with crontab. Sometimes after a reboot the photos do not display until it reboots 6 hours later or if I manually reboot it. I have about 200 photos in my album if that matters. The pictures below show the "no photos problem" when I woke up this morning. It would have been like this for the past 5:15 since the last reboot at midnight. After a quick manual reboot the 2nd picture shows everything is working fine. My MM has been running for about 2 years and this issue has always been present. I believe it is why I started automatically rebooting every 6 hours.

I'm not very good with linux but I can follow directions so please just let me know if you want me to try anything. 

![20220202_051524](https://user-images.githubusercontent.com/74456482/152137660-24043fcc-b364-4dad-9c21-d8d0c29383d8.jpg)
![20220202_051655](https://user-images.githubusercontent.com/74456482/152137672-52ee8b02-0f2b-4f0b-a848-eb173452df3b.jpg)
.

**Comment by rmcelwee** [comment]
OK, I was finally able to get a log of what is happening after running it successfully about 10 times in a row. Can anyone tell me what is going on. This is driving me nuts:

[2022-02-07 08:16:10.910] [LOG]    [GPHOTOS:CORE] Error: getaddrinfo EAI_AGAIN [photoslibrary.googleapis.com](http://photoslibrary.googleapis.com/)
[2022-02-07 08:16:10.918] [ERROR]  (node:1460) UnhandledPromiseRejectionWarning: Error: getaddrinfo EAI_AGAIN [photoslibrary.googleapis.com](http://photoslibrary.googleapis.com/)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
[2022-02-07 08:16:10.923] [ERROR]  (node:1460) UnhandledPromiseRejectionWarning: Error: getaddrinfo EAI_AGAIN [photoslibrary.googleapis.com](http://photoslibrary.googleapis.com/)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
[2022-02-07 08:16:10.925] [ERROR]  (node:1460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[2022-02-07 08:16:10.928] [ERROR]  (node:1460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[2022-02-07 08:16:10.934] [ERROR]  (node:1460) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2022-02-07 08:16:10.938] [ERROR]  (node:1460) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2022-02-07 08:17:15.260] [LOG]    Shutting down server...
[2022-02-07 08:17:15.274] [LOG]    Stopping module helper: MMM-GooglePhotos

**Comment by aneaville** [comment]
Has you updated the Google Photos module in those 2 years?

You are describing issue #78, which led to many changes that improved reliability in 'Robustness Improvements' commit #96.

I expect if you update, this issue will be resolved, and you can probably even stop rebooting every 6 hours. There are other things that you will still want to reboot probably every 48 hours.

If this is on the latest version, then I'll dig in more.

**Comment by rmcelwee** [comment]
It said it was going to update 273 things so I probably haven't updated in the past two years. Upgrading now, I'll post my results if it fixes the problem. FWIW, I had to do a "sudo apt-get update --allow-releaseinfo-change" before it would let me do a "sudo apt-get update" and "sudo apt-get upgrade". 

I appreciate the help!

**Comment by rmcelwee** [comment]
BTW, I also changed my DNS server (was directing the MM to my Pi-Hole) to 8.8.8.8. I read somewhere that it may have been causing the issue. If the issues stop I will put this back to see if the software update was indeed the problem.
