### ISSUE TITLE
generate_token.js error

### ISSUE THREAD

**Issue by Daemuon** [aneaville/MMM-GooglePhotos#138]
When I run: node generate_token.js 
I receive the following:

pi@raspberrypi:~/MagicMirror/modules/MMM-GooglePhotos $ node generate_token.js 
[GPHOTOS:CORE] TypeError: Cannot read property '0' of undefined
/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:133
      throw e
      ^

TypeError: Cannot read property '0' of undefined
    at new Auth (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:35:91)
    at GPhotos.onAuthReady (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:130:14)
    at GPhotos.generateToken (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:141:10)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-GooglePhotos/generate_token.js:10:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

Tried searching but have not found how to fix this.  Thanks.

**Comment by joshcsepegi** [comment]
I am having the same issue. 
worked on a previous install of mmirror.

**Comment by relluts** [comment]
Same issue here. Someone please help

**Comment by pixel-lake** [comment]
Make sure you select "Desktop Client" when you generate OAuth key. That has solved the problem for me.
Can not get past the google authentication though, with "local host resfused to connect" message...

**Comment by phevi0** [comment]
Desktop client made it work for me as well :) 

The localhost refused to connect is normal - you just need the code from the url it redirects you to.

**Comment by Millis-Prime** [comment]
Hi @phevi0 @pixel-lake 
how do i check for desktop client? I have spent hours trying to get this to work

Many Thanks
Ashley.

**Comment by phevi0** [comment]
Set it as Application Type on GCP OAuth client:

![image](https://user-images.githubusercontent.com/50625716/169771055-ea95b899-f412-436e-ba78-28c1b078a103.png)

**Comment by bfr31tas** [comment]
What did the trick for me was:
1. ADD USER in the OAuth consent screen.
2. Generate a NEW OAuth Credentials with Application type as "Desktop app".

Hope this helps.

**Comment by hermanho** [comment]
The token generation is changed in latest version. Please pull the source code and try it. When the problem is still there, please open a new issue.
