### ISSUE TITLE
crashes on latest MM (2.22)     'invalid options argument'

### ISSUE THREAD

**Issue by sdetweil** [aneaville/MMM-GooglePhotos#156]
Latest MM version loads mdkirp V 1.0.4 which is promise based

now get error 
```
 node generate_token_v2.js mkdirp in generate
/home/sam/MagicMirror/node_modules/mkdirp/lib/opts-arg.js:13
    throw new TypeError('invalid options argument')
          ^

TypeError: invalid options argument
    at optsArg (/home/sam/MagicMirror/node_modules/mkdirp/lib/opts-arg.js:13:11)
    at mkdirp (/home/sam/MagicMirror/node_modules/mkdirp/index.js:11:10)
    at generate (/home/sam/MagicMirror/modules/MMM-GooglePhotos/generate_token_v2.js:19:7)
```
mkdirp 1.0.04 s promise based
need to change  generate_token_v2.js code to 
```
      mkdirp(path.dirname(tp)).then( () => {
        fs.writeFileSync(tp, JSON.stringify(client.credentials))
        console.log("Token is generated. check it. (ls -al)")
      })
```

**Comment by sdetweil** [comment]
also in GPhoto.js line 50

**Comment by hermanho** [comment]
Could you please try the dev branch to see if it is fixed?

**Comment by sdetweil** [comment]
looks good
