### ISSUE TITLE
Issue with node generate_token.js

### ISSUE THREAD

**Issue by tails251** [aneaville/MMM-GooglePhotos#164]
I'm trying to make a digital photo frame for a funeral, and am using the MM Tutorial here:  https://www.tomshardware.com/how-to/raspberry-pi-photo-frame

When I get to these commands: 

cd ~/MagicMirror/modules/MMM-GooglePhotos
node generate_token.js

I get the following error:

/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:53
    const oauthClient = new OAuth2Client(key.client_id, key.client_secret, key.redirect_uris[0]);
                                                                                            ^

TypeError: Cannot read properties of undefined (reading '0')
    at Auth.init (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:53:93)
    at new Auth (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:32:10)
    at GPhotos.onAuthReady (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:148:14)
    at GPhotos.generateToken (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:159:10)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-GooglePhotos/generate_token.js:10:9)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

I'm not sure what the cause of this is, as to my knowledge I've correctly followed all instructions to this point (I've also made sure I've installed the most recent versions of everything as some of the versions in this link are old now).

Please could someone advise on some troubleshooting steps to try? I've tried googling and looked through some similar posts on here, but none are quite the same issue. Many thanks in advance, look forward to learning something new!

**Comment by hermanho** [comment]
Please follow with the steps in readme.
https://github.com/hermanho/MMM-GooglePhotos#regular-installation
