### ISSUE TITLE
Sharing scope being deprecated by Google

### ISSUE THREAD

**Issue by chelming** [aneaville/MMM-GooglePhotos#194]
https://github.com/hermanho/MMM-GooglePhotos/blob/843876a2470cb436221ca12aedf794a446778db5/google_auth.json#L4

> We’re making two changes to the Google Photos APIs that will take effect March 31, 2025:
> 1.	Removal of scopes: The [Google Photos Library API](https://notifications.google.com/g/p/ANiao5qdTBK8Rlqi7z-sRGmL2f0VeVhbV9AK6rdZToJ0FsFmciWVnVd1vpgDzKlBkZFNsPxSIMIcHE4umc0_JZUTjsYHPZMDKy_elRcHjB_kgb7sNsUvWfdYQ1i5UVHC3jXQznzX2H0eQAR0DZl4-YabtjBqFDyfZMRkJVDX-y8pw5RCQJN_7ByjW5UaVXAiIMx_UCfsj0DIGjRBLara-l4nx9kDjQ6Ktc6OYPGHL_BegJk_50nT3DdeIxQVeffTIMZTK-2kwU2Pk-hLBQWrCMkcaleAKLMaUaGLxMwthi1qnpN7KpSv83no) readonly, sharing, and search scopes will be removed, with photo picking and search uses cases now supported by a new [Google Photos Picker API](https://notifications.google.com/g/p/ANiao5opG_JSSBt5KXpxj9foM1lB0N97csTEFqDbS21rqw6m2AZTgErjSS05pKVGV9NQx6I7nxN1nMgxmEmPU6LRMfr1cDwBfQcJtZSmF0gpAa5DWGkaqyDAlmjzKnGw6N3E_nXZFtVCfPq5Cciq5Krn7DePNBsEE-_UhgDd9jeWL7hYForzy1TR-_MRjDASHHRNBdo9QsYd8x67M_Z0tbruiRX5U-KKthAy3DqvCusyMIj-nSdak8r1Q0WfEXKsysRS0ytovAdZXZ31k4bvIYjx4vDgxZx1czLmleIlYgUrIAwWFM08).

**Comment by hermanho** [comment]
It is a breaking change 🙁.

1) It have to be selected per photo instead of album.
2) Picker session is validated within 7 days. It is required to download all medias with the session Id to local machine. It is a big different compare with current logic that it can poll and refresh the new photos from the selected albums.

**Comment by hermanho** [comment]
Related issue tracker on Google:
https://issuetracker.google.com/issues/368816420
https://issuetracker.google.com/issues/368779600

**Comment by Jonseed** [comment]
Google's update here: https://developers.google.com/photos/support/updates

In the update it says: "If your app needs users to select photos or _**albums**_ from their entire library, use to the new Google Photos Picker API. This provides a secure and user-friendly way for users to grant access to specific content."

That sounds like you'll still be able to select _**albums**_, not just specific photos, with the new Google Photos Picker API?

**Comment by chelming** [comment]
@Jonseed I think adding an album is a point-in-time operation since, even if you search for an album, you still select individual photos. It's hard to tell though.

https://developers.google.com/photos/picker/guides/picking-experience

**Comment by Jonseed** [comment]
It looks like Google may be creating a separate "digital photo frames" API specific for these kinds of use cases to access Google Photos for "ambient or idle screens." It is unknown whether it will work for non-Google services/products. See these links:

https://support.google.com/photos/thread/326122731?hl=en
https://support.google.com/photos/answer/9458709?sjid=18102457581179128548-NC

**Comment by HitLuca** [comment]
I think I'm seeing the effects of the recent google photos api changes. At startup I now get this error:
```
[2025-04-08 12:47:57.828] [INFO]  Starting Initialization
[2025-04-08 12:47:57.836] [INFO]  Loading cached albumns list
[2025-04-08 12:47:57.859] [INFO]  Loading cached albumns list
[2025-04-08 12:47:59.100] [ERROR] Trace: [GPHOTOS:CORE] request fail with URL mediaItems:batchGet
    at GPhotos.logTrace (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:127:13)
    at GPhotos.request (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:168:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async GPhotos.updateTheseMediaItems (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:296:20)
    at async Class.prepAndSendChunk (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_helper.js:190:16)
    at async Class.tryToIntitialize (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_helper.js:165:9)
[2025-04-08 12:47:59.102] [ERROR] Trace: [GPHOTOS:CORE] params {}
    at GPhotos.logTrace (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:127:13)
    at GPhotos.request (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:169:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async GPhotos.updateTheseMediaItems (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:296:20)
    at async Class.prepAndSendChunk (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_helper.js:190:16)
    at async Class.tryToIntitialize (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_helper.js:165:9)
[2025-04-08 12:47:59.103] [ERROR] Trace: [GPHOTOS:CORE] data null
    at GPhotos.logTrace (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:127:13)
    at GPhotos.request (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:170:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async GPhotos.updateTheseMediaItems (/home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:296:20)
    at async Class.prepAndSendChunk (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_helper.js:190:16)
    at async Class.tryToIntitialize (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_helper.js:165:9)
[2025-04-08 12:47:59.105] [ERROR] [GPHOTOS:CORE] response.data:
{"error":{"code":403,"message":"Request had insufficient authentication scopes.","status":"PERMISSION_DENIED"}}
response.status:
403
headers:
{"vary":"Origin, X-Origin, Referer","content-type":"application/json; charset=UTF-8","date":"Tue, 08 Apr 2025 10:47:58 GMT","server":"ESF","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000","transfer-encoding":"chunked"}
config:
{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http","fetch"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Authorization":"...","User-Agent":"axios/1.7.4","Accept-Encoding":"gzip, compress, deflate, br"},"method":"get","url":"mediaItems:batchGet","baseURL":"https://photoslibrary.googleapis.com/v1/","params":{}}
[2025-04-08 12:47:59.106] [ERROR] failed to refresh and send chunk:
[2025-04-08 12:47:59.108] [ERROR] response.data:
{"error":{"code":403,"message":"Request had insufficient authentication scopes.","status":"PERMISSION_DENIED"}}
response.status:
403
headers:
{"vary":"Origin, X-Origin, Referer","content-type":"application/json; charset=UTF-8","date":"Tue, 08 Apr 2025 10:47:58 GMT","server":"ESF","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000","transfer-encoding":"chunked"}
config:
{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http","fetch"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Authorization":"...","User-Agent":"axios/1.7.4","Accept-Encoding":"gzip, compress, deflate, br"},"method":"get","url":"mediaItems:batchGet","baseURL":"https://photoslibrary.googleapis.com/v1/","params":{}}
```
I received an email mentioning the new Google Photos Picker API, but even after enabling it I cannot get the client to pull pictures on the photo frame

**Comment by chongjae** [comment]
How can i get album read permission?

**Comment by burberius** [comment]
Would be great if you show a message on the main page (via the readme) that the plugin currently is dead due to changes of Google.

**Comment by sethzarny** [comment]
Could you provide a bit more detail in one post that provides the step by step to resolve the problem.  It is hard to tell exactly what is needed to resolve the issue. This is a terrific MMM add-in.  Thank you.

**Comment by chelming** [comment]
@sethzarny there's no fix yet. to resolve this, the project needs to change the API scope used which would require most of the code to pull photos to be changed, too. It's not totally clear what the process for choosing new photos would be and it's possible there will be a new "photo frame" API that could be used.

**Comment by sethzarny** [comment]
> [@sethzarny](https://github.com/sethzarny) there's no fix yet. to resolve this, the project needs to change the API scope used which would require most of the code to pull photos to be changed, too. It's not totally clear what the process for choosing new photos would be and it's possible there will be a new "photo frame" API that could be used.

Thank you.

**Comment by smiles3983** [comment]
update your google_auth.json to this:

`{
  "keyFilePath": "./credentials.json",
  "savedTokensPath": "./token.json",
  "scope": "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
}`

**Comment by shyd** [comment]
That is not true. It only allows you to download data that your app uploaded. We want to access all media. This is not possible anymore.

**Comment by xackery** [comment]
So to confirm:
- This issue still exists and is being investigated the best way to resolve based on google's new directions for API usage
- Until this issue is fixed, this project no longer works. (In my case, I am getting a 403 error in logs when booting up magicmirror2).

edit: just saw this on README, thanks!

**Comment by smiles3983** [comment]
I wish i had time to spend on helping. It is odd that the new rule is only allowing access to pictures that were uploaded by the app that your using to access the photos.  So anything you’ve added to albums using your personal account doesn’t work.  Seems a bit extreme IMO.

**Comment by puitsfraw** [comment]
> I wish i had time to spend on helping. It is odd that the new rule is only allowing access to pictures that were uploaded by the app that your using to access the photos. So anything you’ve added to albums using your personal account doesn’t work. Seems a bit extreme IMO.

Yes it appears the problem still exists.  Looks like no one knows how to fix it.  I personally spent the past week trying to figure out what was going on.  Luckily found this thread acknowledging the problem. It appears to be permanently broken.  I decided to host my photos on my device.  Not as easy to update photos but at least it’s a working solution and won’t break in the future.

**Comment by HitLuca** [comment]
@puitsfraw I personally went with [MMM-ImagesPhotos](https://github.com/roramirez/MMM-ImagesPhotos) and a samba share to put images in. Only gripe with that project is that currently you can't scale pics to fully take up the screen but that's minor

**Comment by chelming** [comment]
@hermanho are images cached locally somewhere that I can just pop new images in a folder as a workaround?

**Comment by puitsfraw** [comment]
> [@puitsfraw](https://github.com/puitsfraw) I personally went with [MMM-ImagesPhotos](https://github.com/roramirez/MMM-ImagesPhotos) and a samba share to put images in. Only gripe with that project is that currently you can't scale pics to fully take up the screen but that's minor

I was having trouble with that module.  I ended up using ChatGPT to help me create a custom module that is almost identical to what I had with the MMM Google Photos except the images are stored on the device.

**Comment by puitsfraw** [comment]
> [@hermanho](https://github.com/hermanho) are images cached locally somewhere that I can just pop new images in a folder as a workaround?

You have to use or create a new module that hosts the images in a folder on your device.  I’m pretty new to all of this but I’ll try to load mine on here later if I can figure it out.  I used ChatGPT to help me create my own custom image module that looks very similar to what I had with the Google Images module.

**Comment by chelming** [comment]
I have to assume there's a cache though since mine keeps displaying photos from the last sync?

**Comment by puitsfraw** [comment]
> I have to assume there's a cache though since mine keeps displaying photos from the last sync?

I’m not really sure. Mine stopped working about two weeks ago after many other people in here have had problems.  I’m wondering if it has something to do with the security token and people having different expiry dates.

**Comment by hermanho** [comment]
> I have to assume there's a cache though since mine keeps displaying photos from the last sync?

Photos are rending with Google URL directly so there is no local cache for those photo files.

**Comment by hermanho** [comment]
> > I have to assume there's a cache though since mine keeps displaying photos from the last sync?
> 
> I’m not really sure. Mine stopped working about two weeks ago after many other people in here have had problems. I’m wondering if it has something to do with the security token and people having different expiry dates.

The expiration time of the access token is 1 hour. It is strange in my MagicMirror. I tried to re-generate a new token file. I could see the two scope in the consent screen. I can use the new token to run the module. It is still working for those API. I think it is depended on the rollout progress from Google side.

![Image](https://github.com/user-attachments/assets/ca060244-5f9c-4237-b749-7b7dc6e0b512)

![Image](https://github.com/user-attachments/assets/7139928f-d123-4618-8695-b90d023da51a)

![Image](https://github.com/user-attachments/assets/fbb4b712-ae40-455a-b144-59d6ab5cb9ee)

**Comment by death2all110** [comment]
Yeah, mine literally just stopped working today because of this issue :(

**Comment by racoonlab** [comment]
I got it working by changing the scope in google_auth.json from
`"scope": "https://www.googleapis.com/auth/photoslibrary https://www.googleapis.com/auth/photoslibrary.sharing"`
to
`"scope": "https://www.googleapis.com/auth/photoslibrary.readonly",`
and then regenerated the token again.
If it expires in an hour, I’ll follow up.

UPDATE
So with the above the token expired after 1h.
So I played a bit...
and there are two key issues in GPhotos.js that explain why token refresh only works during the initial load and not after expiration at runtime.
What's good:
 The class Auth properly loads the credentials and token.
+ it detects expired tokens via tokensCred.expiry_date.
+ It uses oauthClient.refreshAccessToken() to get a new token.
+ it emits the refreshed oauthClient through the "ready" event.
+ It writes the updated token to savedTokensPath.
What's Missing:
a. Auth only refreshes the token once at module start.
-- After that, every time GPhotos.onAuthReady() is called, it creates a new instance of Auth, which:
-- Triggers init()
-- Loads the existing (possibly expired) token
-- Doesn't re-check expiration unless the file is read again
So, the refresh logic runs only once unless the process restarts. And it is not reusing the OAuth2Client or checking token freshness on later API calls.
b. it's not calling client.getAccessToken() before each API call.
Google’s OAuth2Client has built-in token auto-refresh only if we call:
`await client.getAccessToken()`
This ensures that, if the token is expired, it fetches a new one and updates _client.credentials_

The fix:
1. Reuse the OAuth2Client instead of creating a new one every time
Update GPhotos.js to cache the OAuth2Client after it's ready:
```
class GPhotos {
  constructor(options) {
    this.debug = false;
    if (!options.hasOwnProperty("authOption")) {
      throw new Error("Invalid auth information.");
    }
    this.options = options;
    this.debug = options.debug ? options.debug : this.debug;
    this.albums = {
      album: [],
      shared: [],
    };
    this.client = null; // <-- cache here
  }

  async onAuthReady() {
    if (this.client) return this.client; // reuse if already ready

    return new Promise((resolve, reject) => {
      const auth = new Auth(this.options.authOption, this.debug);
      auth.on("ready", (client) => {
        this.client = client;
        resolve(client);
      });
      auth.on("error", (error) => {
        reject(error);
      });
    });
  }

```
2. Call await client.getAccessToken() before every API request:
Update request() method like this:
```
async request(tokenClient, endPoint = "", method = "get", params = null, data = null) {
  try {
    // Ensure the token is still valid and refresh if necessary
    const token = (await tokenClient.getAccessToken()).token;

    let config = {
      method: method,
      url: endPoint,
      baseURL: "https://photoslibrary.googleapis.com/v1/",
      headers: {
        Authorization: "Bearer " + token,
      },
    };
    if (params) config.params = params;
    if (data) config.data = data;

    const ret = await Axios(config);
    return ret;
  } catch (error) {
    this.logTrace("request fail with URL", endPoint);
    this.logTrace("params", JSON.stringify(params));
    this.logTrace("data", JSON.stringify(data));
    this.logError(error_to_string(error));
    throw error;
  }
}
```
Then remove the manual token passing in the method calls like this:
```
const client = await this.onAuthReady();
// Remove: let token = client.credentials.access_token;
await this.request(client, ...);

```
Bonus: Save Refreshed Tokens
oauthClient.refreshAccessToken(); is deprecated, the better approach is to let getAccessToken() refresh it internally, and listen for tokens events:
Inside Auth class init() (after oauthClient.setCredentials(tokensCred)):
```
oauthClient.on('tokens', (tokens) => {
  if (tokens.refresh_token || tokens.access_token) {
    fs.writeFileSync(
      path.resolve(__dirname, this.#config.savedTokensPath),
      JSON.stringify(oauthClient.credentials, null, 2)
    );
    log("Saved refreshed tokens.");
  }
});

```
These changes will:

+ Automatically refresh tokens at runtime
+ Save them back to disk
+ Prevent downtime after token expiration
+ Avoid unnecessary re-authentication or restart

After this, I do not see any more errors in the logs and, for what I can see, it gets new albums:
```
0|mm       | [2025-06-01 19:08:58.335] [INFO]  [GPHOTOS] [node_helper] Got 646 photo(s) from 'Album1'
0|mm       | [2025-06-01 19:08:58.341] [INFO]  [GPHOTOS] [node_helper] Prepare to get photo list from 'Album2'
0|mm       | [2025-06-01 19:09:01.285] [INFO]  [GPHOTOS] [node_helper] Got 53 photo(s) from 'Album2'
0|mm       | [2025-06-01 19:09:01.285] [INFO]  [GPHOTOS] [node_helper] Prepare to get photo list from 'Album3'
0|mm       | [2025-06-01 19:09:02.268] [INFO]  [GPHOTOS] [node_helper] Got 16 photo(s) from 'Album3'
0|mm       | [2025-06-01 19:09:02.268] [INFO]  [GPHOTOS] [node_helper] Total indexed photos: 715
0|mm       | [2025-06-01 19:09:02.353] [INFO]  [GPHOTOS:CORE] received:  50  to refresh
0|mm       | [2025-06-01 19:09:02.363] [INFO]  [GPHOTOS] [node_helper] Next scan will be at 2025-06-01T18:03:31.539Z
```

**Comment by hermanho** [comment]
@racoonlab would you like to make a PR?

**Comment by death2all110** [comment]
> I got it working by changing the scope in google_auth.json from `"scope": "https://www.googleapis.com/auth/photoslibrary https://www.googleapis.com/auth/photoslibrary.sharing"` to `"scope": "https://www.googleapis.com/auth/photoslibrary.readonly",` and then regenerated the token again. If it expires in an hour, I’ll follow up.
> 
> UPDATE So with the above the token expired after 1h. So I played a bit... and there are two key issues in GPhotos.js that explain why token refresh only works during the initial load and not after expiration at runtime. What's good: The class Auth properly loads the credentials and token.
> 
>     * it detects expired tokens via tokensCred.expiry_date.
> 
>     * It uses oauthClient.refreshAccessToken() to get a new token.
> 
>     * it emits the refreshed oauthClient through the "ready" event.
> 
>     * It writes the updated token to savedTokensPath.
>       What's Missing:
>       a. Auth only refreshes the token once at module start.
>       -- After that, every time GPhotos.onAuthReady() is called, it creates a new instance of Auth, which:
>       -- Triggers init()
>       -- Loads the existing (possibly expired) token
>       -- Doesn't re-check expiration unless the file is read again
>       So, the refresh logic runs only once unless the process restarts. And it is not reusing the OAuth2Client or checking token freshness on later API calls.
>       b. it's not calling client.getAccessToken() before each API call.
>       Google’s OAuth2Client has built-in token auto-refresh only if we call:
>       `await client.getAccessToken()`
>       This ensures that, if the token is expired, it fetches a new one and updates _client.credentials_
> 
> 
> The fix:
> 
>     1. Reuse the OAuth2Client instead of creating a new one every time
>        Update GPhotos.js to cache the OAuth2Client after it's ready:
> 
> 
> ```
> class GPhotos {
>   constructor(options) {
>     this.debug = false;
>     if (!options.hasOwnProperty("authOption")) {
>       throw new Error("Invalid auth information.");
>     }
>     this.options = options;
>     this.debug = options.debug ? options.debug : this.debug;
>     this.albums = {
>       album: [],
>       shared: [],
>     };
>     this.client = null; // <-- cache here
>   }
> 
>   async onAuthReady() {
>     if (this.client) return this.client; // reuse if already ready
> 
>     return new Promise((resolve, reject) => {
>       const auth = new Auth(this.options.authOption, this.debug);
>       auth.on("ready", (client) => {
>         this.client = client;
>         resolve(client);
>       });
>       auth.on("error", (error) => {
>         reject(error);
>       });
>     });
>   }
> ```
> 
>     2. Call await client.getAccessToken() before every API request:
>        Update request() method like this:
> 
> 
> ```
> async request(tokenClient, endPoint = "", method = "get", params = null, data = null) {
>   try {
>     // Ensure the token is still valid and refresh if necessary
>     const token = (await tokenClient.getAccessToken()).token;
> 
>     let config = {
>       method: method,
>       url: endPoint,
>       baseURL: "https://photoslibrary.googleapis.com/v1/",
>       headers: {
>         Authorization: "Bearer " + token,
>       },
>     };
>     if (params) config.params = params;
>     if (data) config.data = data;
> 
>     const ret = await Axios(config);
>     return ret;
>   } catch (error) {
>     this.logTrace("request fail with URL", endPoint);
>     this.logTrace("params", JSON.stringify(params));
>     this.logTrace("data", JSON.stringify(data));
>     this.logError(error_to_string(error));
>     throw error;
>   }
> }
> ```
> 
> Then remove the manual token passing in the method calls like this:
> 
> ```
> const client = await this.onAuthReady();
> // Remove: let token = client.credentials.access_token;
> await this.request(client, ...);
> ```
> 
> Bonus: Save Refreshed Tokens oauthClient.refreshAccessToken(); is deprecated, the better approach is to let getAccessToken() refresh it internally, and listen for tokens events: Inside Auth class init() (after oauthClient.setCredentials(tokensCred)):
> 
> ```
> oauthClient.on('tokens', (tokens) => {
>   if (tokens.refresh_token || tokens.access_token) {
>     fs.writeFileSync(
>       path.resolve(__dirname, this.#config.savedTokensPath),
>       JSON.stringify(oauthClient.credentials, null, 2)
>     );
>     log("Saved refreshed tokens.");
>   }
> });
> ```
> 
> These changes will:
> 
>     * Automatically refresh tokens at runtime
> 
>     * Save them back to disk
> 
>     * Prevent downtime after token expiration
> 
>     * Avoid unnecessary re-authentication or restart
> 
> 
> After this, I do not see any more errors in the logs and, for what I can see, it gets new albums:
> 
> ```
> 0|mm       | [2025-06-01 19:08:58.335] [INFO]  [GPHOTOS] [node_helper] Got 646 photo(s) from 'Album1'
> 0|mm       | [2025-06-01 19:08:58.341] [INFO]  [GPHOTOS] [node_helper] Prepare to get photo list from 'Album2'
> 0|mm       | [2025-06-01 19:09:01.285] [INFO]  [GPHOTOS] [node_helper] Got 53 photo(s) from 'Album2'
> 0|mm       | [2025-06-01 19:09:01.285] [INFO]  [GPHOTOS] [node_helper] Prepare to get photo list from 'Album3'
> 0|mm       | [2025-06-01 19:09:02.268] [INFO]  [GPHOTOS] [node_helper] Got 16 photo(s) from 'Album3'
> 0|mm       | [2025-06-01 19:09:02.268] [INFO]  [GPHOTOS] [node_helper] Total indexed photos: 715
> 0|mm       | [2025-06-01 19:09:02.353] [INFO]  [GPHOTOS:CORE] received:  50  to refresh
> 0|mm       | [2025-06-01 19:09:02.363] [INFO]  [GPHOTOS] [node_helper] Next scan will be at 2025-06-01T18:03:31.539Z
> ```

Changing the scope, generating a new token, and restarting magic mirror had no change for me.

photoslibrary.readonly is also impacted by the March 31st changes, so not really a surprise. I still get 403 forbidden. Seems google is doing staged rollouts and mine was impacted recently. 

In my opinion, the new photo picker API really kills the whole point of this as it means users have to go in and pick new photos as they're added, there is no album monitoring. The photo frame/ambient display thing seems to only be for partners, there is basically zero information out there.

Honestly, @hermanho  I wouldn't  put much effort into getting this going again. Google really hamstrung the photos api with this change.

I'm in the process of moving to Immich.

Thank you for your work on this wonderful module, it was great while it lasted.

**Comment by albert63** [comment]
I don't know what happened, but it's been working all of a sudden since this morning.. 
All I did was reinstall the module in the MMM-GooglePhotos folder, just type "npm install" and enter a few days ago..

**Comment by racoonlab** [comment]
> [@racoonlab](https://github.com/racoonlab) would you like to make a PR?

yes, I'll manage later today.

----
UPDATE

@hermanho, today images are no longer loading, and logs show errors, so unfortunately, the PR did not help. Mmm. I'll have another look and test it for more than 48 hours then.

**Comment by albert63** [comment]
> I don't know what happened, but it's been working all of a sudden since this morning.. All I did was reinstall the module in the MMM-GooglePhotos folder, just type "npm install" and enter a few days ago..

It's been working for about a day, and it's broken again

**Comment by Rene20255** [comment]
Hello @death2all110 , I can't start the add-on. I've changed the files, but it still doesn't work. Can you post the finished file here so I can copy and paste it? It would be great if this worked again.

**Comment by bcheng-code** [comment]
Is anyone still working on this?

**Comment by chelming** [comment]
Probably not. Google really screwed people over with the new API.

**Comment by sueya45** [comment]
Is it no longer available? ㅠ.ㅠ

**Comment by bcheng-code** [comment]
> Is it no longer available? ㅠ.ㅠ

I ended up transitioning to this: https://github.com/colindembovsky/MMM-FolderPhotos

**Comment by xackery** [comment]
> > Is it no longer available? ㅠ.ㅠ
> 
> I ended up transitioning to this: https://github.com/colindembovsky/MMM-FolderPhotos

This is an amazing fix thanks for putting the effort!

**Comment by xeonforcecz** [comment]
For anyone landing here because their frame went dark after the March 2025 scope removal — rather than wait on a Picker-API rework I ended up building a full replacement and open-sourced it: **Glassick** — https://github.com/xeonforcecz/glassick (MIT).

Disclosure: it's my own project. How it sidesteps the dead Library API: the importer logs into Google Photos once in a persistent browser session (Playwright) and downloads the shared album's originals into a **local cache** on a nightly timer. The frame only ever reads that local cache, so it keeps working even if Google or the network is down.

It's a from-scratch MagicMirror-style dashboard (not a MM module): full-screen Ken Burns / collage slideshow plus clock, weather (keyless Open-Meteo) and calendar (ICS) overlays, with systemd units + a Chromium kiosk for the Pi.

Fair warning, because it matters: browser automation of Google Photos is a grey area under Google's ToS, so I run it with a **dedicated Google account** that only has the album shared into it — never a primary account. Hope it helps.
